labsec/urls.py
#Django
from django.urls.conf import include
from django.contrib import admin
from django.urls import path
from django.conf.urls import handler400, handler500

handler404 = 'website.views.handler404'
handler500 = 'website.views.handler500'

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('admin/', admin.site.urls),
]

website/urls.py
#Django
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

#Project
from . import views
from .views import ResumoList, ChavesList, GerarCertificado, listaCertificados, CertificadoList, CertificadoRaizList

app_name = "website"

urlpatterns = [
    path('', views.indexFunction, name = 'index'),
    path('exemplos/', views.exemplosFunction, name = 'exemplos'),
    path('getresumo/', ResumoList.as_view(), name='resumo-list'),
    path('resumo/', views.resumoFunction, name = "resumo"),
    path('erros/', views.erroFunction, name = "erro"),
    path('chaves/', views.gerarChaves, name = "chaves"),
    path('getchaves/', ChavesList.as_view(), name='chaves-list'),
    path('getcertificados/', CertificadoList.as_view(), name='certificado-list'),
    path('gerarcertificado/', GerarCertificado.as_view(), name = "gerarcertificado"),
    path('gerarcertificado/raiz', views.gerarCertificadoRaiz, name = "gerarcertificadoraiz"),
    path('certificados/', listaCertificados.as_view(), name = "certificados"),
    path('getcertificadoraiz/', CertificadoRaizList.as_view(), name = "certificado-raiz"),
]

website/forms.py
#Django
from django import forms

#Project
from labsec.models import Certificado

class InsereCertificadoForm(forms.ModelForm):

    class Meta:
        model = Certificado

        fields = [
            'serialNumber',
            'certificateName',
            'organization',
            'organizationalUnit',
            'country',
            'locality',
            'state'
        ]

website/views.py
#Django
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from django.core.files.storage import FileSystemStorage
from rest_framework import generics, status
from rest_framework.response import Response
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from rest_framework.authentication import SessionAuthentication, BasicAuthentication 
from django.template import RequestContext

#Project
from . import process
from labsec.models import Resumo, Chaves, Certificado
from labsec.serializer import ResumoSerializer, ChavesSerializer, CertificadosSerializer, CertificadoRaizSerializer
from .forms import InsereCertificadoForm
from . import db

#Others
import json

#------------------------------------#
'''Erros do Site'''
#------------------------------------#

def handler404(request, *args, **argv):
    response = render(request, 'website/404.html')
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render(request, 'website/500.html')
    response.status_code = 500
    return response

#------------------------------------#
'''Funções do Site'''
#------------------------------------#

def indexFunction(request):
    return render(request, "website/index.html")

def exemplosFunction(request):
    return render(request, "website/exemplos.html")

def erroFunction(request):
    return render(request, "website/erros.html")

def resumoFunction(request):
    contexto = {
        'texto': "Envie um documento para obter seu Resumo Criptográfico",
        'desativado': "true"
    }
    try:
        if request.method == 'POST' and request.FILES['arquivo']:
            #Salva o arquivo em disco para usar no process
            storage = FileSystemStorage(location="files/")
            filename = storage.save(request.FILES['arquivo'].name, request.FILES['arquivo'])
            uploaded_file_url = storage.url(filename)
            up_to_sha = process.upload_to_sha256("files/"+uploaded_file_url)

            contexto = {
                'texto': up_to_sha,
                'ativo': "true"
            }
            try:
                db.insertResumo(filename, up_to_sha, "files/"+uploaded_file_url)
            except:
                print("coe")
    except:
        print("Nenhum arquivo")
    return render(request, "website/resumo.html", contexto)

def gerarChaves(request):
    contexto = {
        'linha_n': 1,
        'linha_e': 1,
        'linha_p': 1,
        'linha_q': 1,
        'linha_d': 1,
        'n': "",
        'e': "",
        'p': "",
        'q': "",
        'd': "",
    }
    if request.method == 'POST':
        key = process.gerarRSAkey(int(request.POST['optradio']))

        if (int(request.POST['optradio']) == 1024):
            contexto = {
                'linha_n': 4,
                'linha_e': 1,
                'linha_p': 2,
                'linha_q': 2,
                'linha_d': 4,
                'n': str(key.n),
                'e': str(key.e),
                'p': str(key.p),
                'q': str(key.q),
                'd': str(key.d), 
            }
        else:
            contexto = {
                'linha_n': 7,
                'linha_e': 1,
                'linha_p': 4,
                'linha_q': 4,
                'linha_d': 7,
                'n': str(key.n),
                'e': str(key.e),
                'p': str(key.p),
                'q': str(key.q),
                'd': str(key.d), 
            }
        
        try:
            db.insertChaves(int(request.POST['optradio']), str(key.n), str(key.e), str(key.p), str(key.q), str(key.d))
        except:
            print("coe")
        
    return render(request, "website/chaves.html", contexto)

def gerarCertificadoRaiz(request):
    if request.method == "POST":
        process.gerarCertificadoRaiz()
    
    #Volta para o index devido a problemas no formulário
    return render(request, "website/index.html")


#------------------------------------#
'''CLasses do Site'''
#------------------------------------#

class listaCertificados(ListView):
    template_name = "website/certificados.html"
    model = Certificado
    context_object_name = "certificados"

class GerarCertificado(CreateView):
    template_name = "website/gerarcertificado.html"
    model = Certificado
    form_class = InsereCertificadoForm
    success_url = reverse_lazy("website:certificados")

    def post(self, request):
        try:
            process.gerarCertificado(request.POST['certificateName'], request.POST['serialNumber'], request.POST['state'], request.POST['country'], request.POST['locality'], request.POST['organization'], request.POST['organizationalUnit'])
        except:
            print("Erro")
        return(super().post(request))

#------------------------------------#
'''CLasses da API'''
#------------------------------------#

class ResumoList(generics.ListCreateAPIView):
    
    queryset = Resumo.objects.all()
    serializer_class = ResumoSerializer
    
    def post(self, request):
        serializer = ResumoSerializer(data=request.data)
        
        if serializer.is_valid():
            serializer.validated_data['nameUpload'] = request.FILES['arquivo'].name
            storage = FileSystemStorage()
            filename = storage.save(request.FILES['arquivo'].name, request.FILES['arquivo'])
            resumo = process.upload_to_sha256(filename)
            serializer.validated_data['resumoCriptografico'] = resumo
            process.deletefile(filename)
            serializer.save()
            retorno = {
                'nameUpload' : filename,
                'resumoCriptografico' : resumo
            }
            return Response(json.dumps(retorno, sort_keys=True, indent=4), status=status.HTTP_201_CREATED)
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

class ChavesList(generics.ListCreateAPIView):
    
    queryset = Chaves.objects.all()
    serializer_class = ChavesSerializer

    def post(self, request):
        serializer = ChavesSerializer(data=request.data)
        if serializer.is_valid():
            key = process.gerarRSAkey(int(request.data['tipo']))
            serializer.validated_data['n'] = str(key.n)
            serializer.validated_data['e'] = str(key.e)
            serializer.validated_data['p'] = str(key.p)
            serializer.validated_data['q'] = str(key.q)
            serializer.validated_data['d'] = str(key.d)
            serializer.save()
            retorno = {
                'tipo': int(request.data['tipo']),
                'n': str(key.n),
                'e': str(key.e),
                'p': str(key.p),
                'q': str(key.q),
                'd': str(key.d), 
            }
            return Response(json.dumps(retorno, sort_keys=True, indent=4), status=status.HTTP_201_CREATED)
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

class CertificadoList(generics.ListCreateAPIView):

    queryset = Certificado.objects.all()
    serializer_class = CertificadosSerializer

    def post(self, request):
        serializer = CertificadosSerializer(data=request.data)
        if serializer.is_valid():
            process.gerarCertificado(request.POST['certificateName'], request.POST['serialNumber'], request.POST['state'], request.POST['country'], request.POST['locality'], request.POST['organization'], request.POST['organizationalUnit'])
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class CertificadoRaizList(generics.CreateAPIView):

    serializer_class = CertificadoRaizSerializer

    def post(self, request):
        retorno = process.gerarCertificadoRaiz()
        if retorno == 0:
            return Response({'CREATE': 'OK'}, status=status.HTTP_201_CREATED)
        else:
            return Response({'CREATE': 'EXIST'}, status=status.HTTP_200_OK)

website/templates/website/certificados.html
{% extends "website/_layouts/base.html" %}

{% block title %} Lista de Certificados {% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Certificados</h5>

          {% if certificados|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Certificados</code> emitidos.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th>Serial</th>
                <th>Certificate Name</th>
                <th>Organization</th>
                <th>Organization Unit</th>
                <th>Country</th>
                <th>Locality</th>
                <th>State</th>
              </tr>
              </thead>

              <tbody>
              {% for certificado in certificados %}
                <tr>
                  <td>{{ certificado.serialNumber }}</td>
                  <td>{{ certificado.certificateName }}</td>
                  <td>{{ certificado.organization }}</td>
                  <td>{{ certificado.organizationalUnit }}</td>
                  <td>{{ certificado.country }}</td>
                  <td>{{ certificado.locality }}</td>
                  <td>{{ certificado.state }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Certificado</code> foi emitido ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:gerarcertificado' %}" class="btn btn-dark">
              Emitir Novo Certificado
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/chaves.html
{% extends "website/_layouts/base.html" %}

{% block title %} Gerar Chaves {% endblock %}

{% block conteudo %}

<div class = "container-fluid">
    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Gerar Chaves Assimétricas com RSA</h5>
                    <p class="card-text">
                        <b>Para melhor visualização, as <code>Chaves Assimétricas</code> geradas serão mostradas na tela.</b><br>
                        <b>*A geração com 2048 bits pode demorar um pouco.</b>
                        <hr>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "chavesrow">
        <div class = "col">
            <div class = "card">
                <form method="POST" id = "formchave">
                    {% csrf_token %}
                    <center><div class="radio">
                        <label><input type="radio" value = "1024" id = "radio1" name="optradio" checked>1024 bits</label>
                        <label><input type="radio" value = "2048" id = "radio2" name="optradio">2048 bits</label>
                    </div></center>
                    <button type="submit" class="btn btn-dark btn-sm btn-block">Gerar Chave</button>
                </form>
                <div class = "card body">
                    <div class = "divchave">
                        <h5 class="card-title">Chave Pública (n,e)</h5>
                        <p class="card-text">
                            <code>(n)</code>
                        </p>

                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="{{linha_n}}">{{n}}</textarea>
                        <p class="card-text">
                            <code>(e)</code>
                        </p>

                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="{{linha_e}}">{{e}}</textarea>
                    </div>
                    
                    <div class = "divchave" id = "divprivada">
                        <h5 class="card-title">Chave Privada (p,q,d)</h5>
                        <p class="card-text">
                            <code>(p)</code>
                        </p>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="{{linha_p}}">{{p}}</textarea>
    
                        <p class="card-text">
                            <code>(q)</code>
                        </p>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="{{linha_q}}">{{q}}</textarea>
    
                        <p class="card-text">
                            <code>(d)</code>
                        </p>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="{{linha_d}}">{{d}}</textarea>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/website/erros.html
{% extends "website/_layouts/base.html" %}

{% block title %} Exemplos API {% endblock %}

{% block conteudo %}
<div class = "container-fluid">
    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Status Code</h5>
                    <p class="card-text">
                        <b><code>201</code> - Funcionou porém arquivo já existe.</b><br>
                        <b><code>201</code> - Funcionou e arquivo criado.</b><br>
                        <b><code>400</code> - Bad Request. Algum campo foi preenchido incorretamente ou está faltando.</b>
                        <hr>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">CSRF</h5>
                    <h6 class = "erros">Caso esteja com problemas para realizar os requests, envie um dado com o token do csrf junto com o request.</h6>
                    <h6 class = "erros"><code>Exemplo</code></h6>
                    <div class = "codigo">
                        <p class="card-text">
                            import <code>requests</code><br>
                            ses = requests.Session()<br>
                            r = ses.get('http://localhost:8000/resumo/')<br>
                            csrf_token = r.cookies['csrftoken']<br>
                            info = {'csrfmiddlewaretoken': csrf_token}<br>
                            send = {<br>
                            'arquivo' : (nomeArquivo, open(nomeArquivo, 'rb'), 'multipart/form-data')<br>
                            }<br>
                            requests.post('http://localhost:8000/getresumo/', files = send, data=info)<br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

website/templates/website/exemplos.html
{% extends "website/_layouts/base.html" %}

{% block title %} Exemplos API {% endblock %}

{% block conteudo %}
<div class = "container-fluid">
    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Exemplos</h5>
                    <p class="card-text">
                        <b>Serão mostradas alguns exemplos de <code>Requisições</code> para exemplificar o uso da API.</b><br>
                        <b>Os exemplos são na linguagem Python e utilizando a library requests.</b><br>
                        Para instalar a library requests use <code>pip install requests</code><br>
                        *Para problemas com CSRF, consulte o ultimo bloco.
                        <hr>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Resumo Criptográfico</h5>
                    <div class = "codigo">
                        <p class="card-text">
                            import <code>requests</code><br>
                            send = {<br>
                            'arquivo' : (nomeArquivo, open(nomeArquivo, 'rb'), 'multipart/form-data')<br>
                            }<br>
                            resumo = requests.post('http://localhost:8000/getresumo/', files = send)<br>
                            resumo.json()
                        </p>
                    </div>
                    <div class = "codigo" id = "get1">
                        <p class="card-text">
                            import <code>requests</code><br>
                            resumos = requests.get('http://localhost:8000/getresumo/')<br>
                            resumos.json()
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Chaves Assimétricas</h5>
                    <div class = "codigo">
                        <p class="card-text">
                            import <code>requests</code><br>
                            send = {<br>
                            'tipo' : 2048<br>
                            }<br>
                            chaves = requests.post('http://localhost:8000/getchaves/', data = send)<br>
                            chaves.json()
                        </p>
                    </div>
                    <div class = "codigo" id = "get1">
                        <p class="card-text">
                            import <code>requests</code><br>
                            chaves = requests.get('http://localhost:8000/getchaves/')<br>
                            chaves.json()
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Certificados</h5>
                    <div class = "codigo">
                        <p class="card-text">
                            import <code>requests</code><br>
                            send = {<br>
                            'serialNumber' : 1234, <br>
                            'certificateName' : 'name', <br>
                            'organization' : 'organization',<br>
                            'organizationalUnit' : 'organizationalUnit',<br>
                            'country' : 'BR',<br>
                            'locality' : 'locality',<br>
                            'state' : 'state'<br>
                            }<br>
                            certificados = requests.post('http://localhost:8000/getcertificados/', data = send)<br>
                            certificados.json()
                        </p>
                    </div>
                    <div class = "codigo" id = "get1">
                        <p class="card-text">
                            import <code>requests</code><br>
                            certificados = requests.get('http://localhost:8000/getcertificados/')<br>
                            certificados.json()
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Certificado Raiz</h5>
                    <div class = "codigo" id = "get1">
                        <p class="card-text">
                            import <code>requests</code><br>
                            certificados = requests.post('http://localhost:8000/getcertificadoraiz/')<br>
                            certificados.json()
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/gerarcertificado.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %} Gerar Certificado {% endblock %}

{% block conteudo %}

<div class = "container-fluid">
    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Emitir Certificado X-509 para a AC-Raiz</h5>
                    <p class="card-text">
                        <b>Caso já exista um <code>Certificado</code> da AC-Raiz, um novo certificado não será emitido.</b><br>
                    </p>
                </div>
                <form method="POST" action="{% url 'website:gerarcertificadoraiz' %}" class = "formacraiz">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark btn-sm btn-block" >Emitir Certificado para AC-Raiz</button>
                </form>
                <hr>
            </div>
        </div>
    </div>

    <div class = "row" id = "rowchave">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Emitir Certificado X-509 assinado pela AC-Raiz</h5>
                    <p class="card-text">
                        <b>Emitir um novo <code>Certificado</code> assinado pela AC-Raiz.</b><br>
                    </p>
                </div>
                <form method="POST" class = "formacraiz">
                    {% csrf_token %}
                    <div class="form-row" id = "formcert">
                        <div class="form-group col-md-6">
                            <label for="certname">Certificate Name</label>
                            {% render_field form.certificateName class+="form-control" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="serialnum">Serial Number</label>
                            {% render_field form.serialNumber class+="form-control" %}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="city">Country</label>
                            {% render_field form.country class+="form-control" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="state">State</label>
                            {% render_field form.state class+="form-control" %}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="local">Locality</label>
                        {% render_field form.locality class+="form-control" %}
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="org">Organization</label>
                            {% render_field form.organization class+="form-control" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="orgunit">Organizational Unit</label>
                            {% render_field form.organizationalUnit class+="form-control" %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-dark btn-sm btn-block" id = "buttoncert" >Emitir Certificado</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/website/index.html
{% extends "website/_layouts/base.html" %}

{% block title %} LabSec {% endblock %}

{% block conteudo %}

<div class = "container-fluid">
    <div class = "row">
        <div class = "col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Resumo Criptográfico</h5>
                    <p class="card-text">
                        Obter o <code>Resumo Criptográfico</code> de um documento.
                    </p>
                    <a href="{% url 'website:resumo' %}"
                        class="btn btn-dark btn-sm">
                        Resumo Criptográfico
                    </a>
                </div>
            </div>
        </div>

        <div class = "col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class = "card">
                    <div class = "card body">
                        <h5 class="card-title">Chave Assimétrica</h5>
                        <p class="card-text" >
                        Gerar <code>Chaves Assimétricas</code> usando RSA.
                        </p>
                        <a href="{% url 'website:chaves' %}"
                        class="btn btn-dark btn-sm">
                        Gerar Chave Assimétrica
                        </a>
                    </div>
                </div>
            </div>
    </div>

    <div class = "row">
            <div class = "col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class = "card">
                    <div class = "card body">
                        <h5 class="card-title">Certificado Digital</h5>
                        <p class="card-text">
                        Gerar um <code>Certificado Digital</code>.
                        </p>
                        <a href="{% url 'website:gerarcertificado' %}"
                        class="btn btn-dark btn-sm">
                        Gerar Certificado
                        </a>
                    </div>
                </div>
            </div>

            <div class = "col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class = "card">
                        <div class = "card body">
                            <h5 class="card-title">Lista de Certificados Digitais</h5>
                            <p class="card-text" >
                            Obter a <code>Lista de Certificados Digitais</code> gerados.
                            </p>
                            <a href="{% url 'website:certificados' %}"
                            class="btn btn-dark btn-sm">
                            Lista de Certificados
                            </a>
                        </div>
                    </div>
            </div>
    </div>
    <hr>
    <div class = "col">
        <div class = "card">
            <div class = "card body">
                <h5 class="card-title">API</h5>
                <p class="card-text" >
                O site foi criado para facilitar a visualização das informações e tornar o sistema um pouco mais interativo.<br>
                Os links abaixo levam a páginas da API de cada ferramenta desenvolvida, sendo possivel enviar requisições via <code>POST</code> ou obter informações pelo <code>GET</code>.<br>
                As informações obtidas podem ser obtidas de um arquivo <code>JSON</code>. Divirta-se.
            </div>
        </div>
    </div>

    <div class = "row" id = "indexx">
        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Resumo Criptográfico</h5>
                    <a href="{% url 'website:resumo-list' %}"
                    class="btn btn-primary btn-sm">
                    API Resumo
                    </a>
                </div>
            </div>
        </div>

        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Chave Assimétrica</h5>
                    <a href="{% url 'website:chaves-list' %}"
                    class="btn btn-success btn-sm">
                    API Chave
                    </a>
                </div>
            </div>
        </div>

        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Certificado Digital</h5>
                    <a href="{% url 'website:certificado-list' %}"
                    class="btn btn-danger btn-sm">
                    API Certificados
                    </a>
                </div>
            </div>
        </div>

        <div class = "col">
            <div class = "card">
                <div class = "card body">
                    <h5 class="card-title">Certificado AC-Raiz</h5>
                    <a href="{% url 'website:certificado-raiz' %}"
                    class="btn btn-danger btn-sm">
                    API AC-Raiz
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}